### PR TITLE
WIP- Backend and Frontend updates after review on PR #199

### PR DESCRIPTION
**Pull request by ishangupta-ds**
Fixes icon fullscreen.svg, made analytics API modular, added leap year check and formatted yaml_linter files.

### CODE REVIEW

**Comment by gdsoumya** [comment]
There are frontend changes here, we need the backend first then you can make the required changes to frontend later. The changes requested in the frontend haven't been done in this PR. PTAL @ishangupta-ds

**Comment by ishangupta-ds** [comment]
> There are frontend changes here, we need the backend first then you can make the required changes to frontend later. The changes requested in the frontend haven't been done in this PR. PTAL @ishangupta-ds

I have already made the changes requested in the frontend. Using a completely different library will take time we can till then have it merged as this is just the staging branch we can test the editor here till we come up with an alternative for yaml parsing.

**Comment by ishangupta-ds** [comment]
> There are frontend changes here, we need the backend first then you can make the required changes to frontend later. The changes requested in the frontend(yaml-package) haven't been done in this PR. PTAL @ishangupta-ds

Other minor changes to frontend as requested by @rajdas98 have been made.

**Comment by ishangupta-ds** [comment]
> Future Changes Required:
> 
> 1. Update Yaml-Parser Package [frontend]

Yes that will be done next along with minor ui fixes.

**Comment by rajdas98** [comment]
Is analytics backend required yaml-lint or other frontend changes? Can't it be specific to analytics backend

**Comment by gdsoumya** [comment]
> Is analytics backend required yaml-lint or other frontend changes? Can't it be specific to an analytics backend changes

Frontend is not necessary. If we merge the front-end changes too, it will be difficult to cherrypick backend changes to master as all the changes are in 1 commit.

**Comment by rajdas98** [comment]
@ishangupta-ds Can you put only analytics backend changes? The YAML lint js files required some review from @chandankumar4 .

**Comment by rajdas98** [comment]
And also update the PR title specific to your changes

**Comment by ishangupta-ds** [comment]
Okay I will do it asap.

**Comment by ishangupta-ds** [comment]
> And also update the PR title specific to your changes

Its done you can review the PR #202 . @rajdas98

**Comment by ishangupta-ds** [comment]
@chandankumar4 can you review the frontend code for this PR.

**Comment by ishangupta-ds** [comment]
> @ishangupta-ds Can you put only analytics backend changes? The YAML lint js files required some review from @chandankumar4 .

cc @chandankumar4 For the inting purposes its necessary to override the parser thus i have made a custom linter overriding the parser from 'react-ace' its an open source node package with MIT License and is widely used for building custom text editors due to its many customization options.

**Pull request closed without merging**
