### PR TITLE
(ui-frontend-implementation): Changing breadcrumbs on charts and experiments #787

### PR DESCRIPTION
**Pull request by mohatagarvit**
Fixes litmuschaos/litmus#787

Changes styling of Breadcrumbs for Charts, Experiments and Subcharts
image

Signed-off by: Garvit Mohata mohatagarvit@gmail.com

### CODE REVIEW

**Comment by chandankumar4** [comment]
@mohatagarvit There is some conflict in the PR can you resolve that.

**Comment by mohatagarvit** [comment]
@chandankumar4 I made the same changes as before but I am not able to run the server. It throws this error.
image
So, I can't provide a screenshot of how it looks now. Is the server working fine for you?

**Comment by chandankumar4** [comment]
> @chandankumar4 I made the same changes as before but I am not able to run the server. It throws this error.
> image
> So, I can't provide a screenshot of how it looks now.
> 
> The same files were working fine a week back. And they have not been modified. So, I am not able to understand the problem.
> Is the server working fine for you?

Yes all are good for us, Can you pull this PR changes again can try it.
@aditya109 Can you help him

**Comment by aditya109** [comment]
> @chandankumar4 I made the same changes as before but I am not able to run the server. It throws this error.
> image
> So, I can't provide a screenshot of how it looks now.
> 
> The same files were working fine a week back. And they have not been modified. So, I am not able to understand the problem.
> Is the server working fine for you?

Hi @mohatagarvit, we will have it fixed by noon. Please rebase your branch.

**Comment by mohatagarvit** [comment]
Sorry for the delay. Is it fine now?

**Comment by NisantaSahoo** [comment]
Thanks for taking part in Hacktoberfest 2019. Please fill up this form to claim your swag https://hubs.ly/H0l5ldm0

**Pull request merged**
