### PR TITLE
Update Installation and Usage instructions in README.md

### PR DESCRIPTION
**Pull request by agarwalrounak**
Fixes https://github.com/litmuschaos/litmus/issues/821

Signed-off-by: Rounak Agarwal <rounakr.ag73@gmail.com>

### CODE REVIEW

**Comment by ksatchit** [comment]
@aditya109 @inyee786 could you please take a look?

**Comment by inyee786** [comment]
hi @agarwalrounak,
can change base branch to `staging`

**Comment by agarwalrounak** [comment]
Hi @inyee786, I have changed the base branch to `staging`. Let me know if any more changes are needed.

**Comment by inyee786** [comment]
will review your pr once this pr get merged:
https://github.com/litmuschaos/charthub.litmuschaos.io/pull/34

**Comment by NisantaSahoo** [comment]
Thanks for taking part in Hacktoberfest 2019. Please fill up this form to claim your swag https://hubs.ly/H0l5ldm0

**Pull request merged**
