### PR TITLE
Fix mobile view of Generic charts

### PR DESCRIPTION
**Pull request by agarwalrounak**
Fixes https://github.com/litmuschaos/litmus/issues/819

The chaos experiments are now stacked one below the other in mobile view. 

### Before:
Screenshot from 2019-10-06 19-39-29

### After:
newc

Signed-off-by: Rounak Agarwal <rounakr.ag73@gmail.com>

### CODE REVIEW

**Comment by ksatchit** [comment]
cc: @aditya109 @inyee786

**Comment by inyee786** [comment]
@agarwalrounak ,
can change base branch to `staging`

**Comment by agarwalrounak** [comment]
Hi @inyee786, I have changed the base branch to `staging`. Let me know if there are any more changes to be done.

**Comment by NisantaSahoo** [comment]
Thanks for taking part in Hacktoberfest 2019. Please fill up this form to claim your swag https://hubs.ly/H0l5ldm0

**Pull request merged**
