### PR TITLE
Cherry pick  commits from staging to master

### PR DESCRIPTION
**Pull request by gdsoumya**
Cherry Pick commits from staging to master

Commits taken :

- 6e083715a4a665d5f3f96a9c7604775bf8edbd2b
- 7db1288732cbd4ff4d5fca2dfb920b2be2460845
- 6ee0576d5f22cd2b8eead85462acac169968fbc4
- 23b6180026be3ae4ffa972fd354ef69e7885a476
- 23b6180026be3ae4ffa972fd354ef69e7885a476
- 0c5a422578304df0b22f4a2ae85a2e6b77e7d9e9
- c1f7cde3bf808d96a6a3187ada424d9bda0b1d72
- 29ee6fabcf1d6609262a99fe0c617f528d410f34

### CODE REVIEW

**Comment by chandankumar4** [comment]
Can we make the link as clickable in comment.

**Comment by gdsoumya** [comment]
> Can we make the link as clickable in comment and also is it possible to expire the link after 2-3 days?

Yes it is possible to set the time, currently the links are not clickable but it can surely be done. To set time use `/preview <time-in-mins>`

**Pull request merged**
