### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by aadu999**
Made the code blocks easier to copy and fixed typo in Readme.

### CODE REVIEW

**Comment by inyee786** [comment]
@aadu999 ,
can you change base branch to `staging`

**Comment by inyee786** [comment]
@aadu999, can plz resolve your pull request

**Comment by aditya109** [comment]
@aadu999 can you please sign your commit which is the reason why DCO is failing.

**Comment by chandankumar4** [comment]
As no response from the user! Closing this PR
Reference PR: https://github.com/litmuschaos/charthub.litmuschaos.io/pull/38

**Pull request closed without merging**
