### PR TITLE
fixed Dockerfile.server, added docker-compose.yml

### PR DESCRIPTION
**Pull request by kmjayadeep**
Added docker compose file and fixed dockerfile.server

Closes litmuschaos/litmus#806
Closes litmuschaos/litmus#807

Changes:

- Removed Unnecessary mkdir commands in dockerfile
- Combined multi line commands into single line (go get commands)
- Added docker-compose.yml file
- Updated readme for running the application in docker

Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

### CODE REVIEW

**Comment by inyee786** [comment]
@kmjayadeep, did you tested it?

**Comment by kmjayadeep** [comment]
Yes I have. Everything is working smoothly

**Comment by kmjayadeep** [comment]
I have one suggestion though. It would be better to change port from 80 to 3000 or something like that. It is just a one line change in compose file

**Comment by inyee786** [comment]
@kmjayadeep,
can you change base branch to `staging`

**Comment by kmjayadeep** [comment]
> @kmjayadeep,
> can you change base branch to `staging`

Done

**Comment by kmjayadeep** [comment]
@inyee786 @aditya109 Is there anything else to be done?

**Comment by aditya109** [comment]
> @inyee786 @aditya109 Is there anything else to be done?

@kmjayadeep everything is working fine. Lastly I just want if you can star the litmus repo [https://github.com/litmuschaos/litmus]()

**Comment by rajdas98** [comment]
@kmjayadeep  Can post the docker logs in this PR?

**Comment by rajdas98** [comment]
@kmjayadeep Can you do ```docker logs CONTAINER_NAME >> logs.txt``` ?
and send the ```logs.txt``` in this PR.

**Comment by rajdas98** [comment]
@kmjayadeep LGTM. @aditya109 @inyee786 you can merge it.

**Comment by NisantaSahoo** [comment]
Thanks for taking part in Hacktoberfest 2019. Please fill up this form to claim your swag https://hubs.ly/H0l5ldm0

**Pull request merged**
