### PR TITLE
New logos for pod-delete and container-kill

### PR DESCRIPTION
**Pull request by ven-k**
This PR is a follow up of #873 and #874 of litmuschaos/litmus. 

A new folder, "icons" is added to "server/charts/generic" and logos for pod-delete and container-kill (in both png and svg) are added, as per the instructions in #879.

### CODE REVIEW

**Comment by ven-k** [comment]
I've added a new logo for net-latency. Please see @aditya109.

**Comment by aditya109** [comment]
> I've added a new logo for net-latency. Please see @aditya109.

Hi @ven-k we have a small request. So there was a small change in our [charthub structure](https://github.com/litmuschaos/charthub.litmuschaos.io) and the icons have been to other repository. So can you please add these icons to `generic > icons` directory and raise a PR at [chao-charts](https://github.com/litmuschaos/chaos-charts) ?

**Comment by aditya109** [comment]
> > I've added a new logo for net-latency. Please see @aditya109.
> 
> Hi @ven-k we have a small request. So there was a small change in our [charthub structure](https://github.com/litmuschaos/charthub.litmuschaos.io) and the icons have been to other repository. So can you please add these icons to `generic > icons` directory and raise a PR at [chao-charts](https://github.com/litmuschaos/chaos-charts) ? Also, you might need to add one more icon for the experiment network-loss.
> 
> > Note :
> > Please rename the icons exactly as they have been named in the folder.

**Comment by aditya109** [comment]
Also are you interested in designing logos for openebs experiments as well ?  I can make an issue and assign it you. Please take a look at our [hub](https://hub.litmuschaos.io).

**Comment by aditya109** [comment]
@ven-k Since you are unable to work on the improvements, so I am closing this PR and we will pick icons from here when the requirement comes up. In order to receive the **hacktoberfest-goodies**, please fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSc9jHp7RXP1s1pUNsdexZk3o3Da4qBCpUHn_paW6r5KcfTX6w/viewform).

**Comment by ven-k** [comment]
@aditya109, I did work on the network loss icon, but it wasn't up to my satisfaction; so I never committed the icon to the existing PR. Thank you for the efforts and appreciation to the entire team.

**Comment by aditya109** [comment]
Still, it is great work. Please continue to contribute in your open source journey. :)

**Pull request closed without merging**
