### PR TITLE
added version details in the side panel

### PR DESCRIPTION
**Pull request by kmjayadeep**
Closes litmuschaos/litmus#788

Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

### CODE REVIEW

**Comment by inyee786** [comment]
@kmjayadeep, it will be great if you put a screenshot of the UI

**Comment by kmjayadeep** [comment]
image

**Comment by inyee786** [comment]
@kmjayadeep,
can you change base branch to `staging`

**Comment by kmjayadeep** [comment]
> @kmjayadeep,
> can you change base branch to `staging`

Done

**Comment by kmjayadeep** [comment]
@inyee786 @aditya109 Is there anything else to be done?

**Pull request merged**
