### PR TITLE
WIP: bug-fix: fixed type checking for js files.

### PR DESCRIPTION
**Pull request by ishangupta-ds**
Fixed type checking for js files hampering production build and deployment.

fixes #206

### CODE REVIEW

**Comment by ishangupta-ds** [comment]
@chandankumar4 PTAL.

**Comment by chandankumar4** [comment]
Can you fix the commits, It should contain only one commit

**Comment by ishangupta-ds** [comment]
> Can you fix the commits, It should contain only one commit

You can squash them into 1, i had to update my fork' staging branch with the changes so they have come in.

**Comment by arkajyotiMukherjee** [comment]
If you are sure this is the bug...try adding this too
allowJS: true 
in tsconfig @ishangupta-ds

**Comment by ishangupta-ds** [comment]
> If you are sure this is the bug...try adding this too
> allowJS: true
> in tsconfig @ishangupta-ds

Its already added **"allowJs": true,** in the tsconfig.json

**Comment by ishangupta-ds** [comment]
> If you are sure this is the bug...try adding this too
> allowJS: true
> in tsconfig @ishangupta-ds

You can add this parameter also for the litmus portal..it may solve the issue with GeoMap and also wont throw errors while integrating the Yaml Editor there.

"compilerOptions": {
	"checkJs": false,
 }

@arkajyotiMukherjee

**Comment by gdsoumya** [comment]
It's still not working please build the files in the local and check. It's throwing error. Check the console for the error.

**Comment by arkajyotiMukherjee** [comment]
@ishangupta-ds the build is not working run `npm run build` in your local system and check.

**Comment by ishangupta-ds** [comment]
A minor fix has been added can you preview it again with better.ci @gdsoumya

**Comment by ishangupta-ds** [comment]
> @ishangupta-ds the build is not working run `npm run build` in your local system and check.

It is building correctly on my local system now.

**Comment by ishangupta-ds** [comment]
> It's still not working please build the files in the local and check. It's throwing error. Check the console for the error. @ishangupta-ds

npm run build is working locally.

**Comment by arkajyotiMukherjee** [comment]
@ishangupta-ds Don't add commits one after the other...check in your local system please...and if you use `alwaysStrct: false` in tsconfig it'll introduce a lot of bad code in the typescript files.

**Comment by ishangupta-ds** [comment]
Please verify the travis.ci build too its passing. @gdsoumya @arkajyotiMukherjee .

**Comment by ishangupta-ds** [comment]
> @ishangupta-ds Don't add commits one after the other...check in your local system please...and if you use `alwaysStrct: false` in tsconfig it'll introduce a lot of bad code in the typescript files.

actually it will be by default in "use strict" mode but can be overridden with "no use strict".

**Comment by arkajyotiMukherjee** [comment]
This is not a CI problem...your built code is failing...run npm run build to test in your local system...the error is in ace editor

**Comment by gdsoumya** [comment]
@ishangupta-ds check the preview it's still not working. Verify on your system and make the PRs.

**Comment by ishangupta-ds** [comment]
Its working on local system now but not on deployment. I am verifying with each change to tsconfig.

**Comment by ishangupta-ds** [comment]
Don't merge it now we will have to fix the deployment issue.

**Comment by ishangupta-ds** [comment]
can you launch a preview now? @gdsoumya

**Comment by gdsoumya** [comment]
@ishangupta-ds still not working

**Comment by ishangupta-ds** [comment]
Okay let @arkajyotiMukherjee have a look at it after this release.

**Pull request closed without merging**
